Arch_GestTask.MVC/Controllers/PersonneController.cs
using Arch_GestTask.MVC.Models.Mappers;
using Arch_GestTask.MVC.Models.Personne;
using Arch_GestTask.MVC.Models.Tache;
using ArchNet_GestTask.Domains.Commands;
using TaskModel = ArchNet_GestTask.Domains.Entities.Task;
using ArchNet_GestTask.Domains.Queries;
using ArchNet_GestTask.Domains.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Arch_GestTask.MVC.Controllers
{
    public class PersonneController : Controller
    {
        private readonly IPersonneRepository _personRepository;
        private readonly ITaskRepository _taskRepository;

        public PersonneController(IPersonneRepository personRepository, ITaskRepository taskRepository)
        {
            _personRepository = personRepository;
            _taskRepository = taskRepository;
        }

        public IActionResult Index()
        {

            var response = _personRepository.Execute(new GetAllPersonneQuery());

            if (response.IsSuccess && response.Result!.Count() > 0)
            {
                List<PersonDisplayForm> people = response.Result.Select(p => p.ToPersonDisplay()).ToList();    
            return View(people);
                
            }

            return View();

        }

       public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreatePersonForm form) {

            if (ModelState.IsValid)
            {
                var response = _personRepository.Execute(new ArchNet_GestTask.Domains.Commands.CreatePersonneCommand(form.Name, form.Surname));
                if (response.IsSuccess) 
                    return RedirectToAction("Index");
            }

            return View();
        }


        // TODO
        public IActionResult Edit(int id)
        {
            var response = _personRepository.Execute(new GetOnePersonQuery(id));

            UpdatePersonForm person = response.Result.ToUpdatePerson();
            if (response.IsSuccess)
                return View(person);

            return View();
        }

        [HttpPost]
        public IActionResult Edit(UpdatePersonForm form, int id)
        {
            var response = _personRepository.Execute(new UpdatePersonneCommand(id, form.Name, form.Surname));
            if (response.IsSuccess)
                return RedirectToAction("Index");

            return View();
        }

        public IActionResult PersonneEtTache()
        {
			var response = _personRepository.Execute(new GetAllPersonneQuery());
			if (response.IsSuccess && response.Result!.Count() > 0)
			{
				List<PersonneEtTacheDisplayForm> people = response.Result.Select(p => p.ToPersonEtTaskDisplay()).ToList();

                foreach (var item in people)
                {
                    var taskResponse = _taskRepository.Execute(new GetTaskByPersonQuery(item.PersonId));
                    if (taskResponse.Result != null)
                    {
                    foreach (var task in taskResponse.Result)
                    {
                            item.Tasks.Add(task.ToTaskDisplayDetail());
                                
                        
                    }
                        
                    }
                };
                return View(people);

			}

			return View();
		}
        public IActionResult PartialTask()
        {
            return new PartialViewResult
            {
                ViewName = "_PartialTask"
            };
        }
    }
}

Arch_GestTask.MVC/Controllers/TacheController.cs
using Arch_GestTask.MVC.Models.Mappers;
using Arch_GestTask.MVC.Models.Tache;
using ArchNet_GestTask.Domains.Commands;
using ArchNet_GestTask.Domains.Entities;
using ArchNet_GestTask.Domains.Queries;
using ArchNet_GestTask.Domains.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Arch_GestTask.MVC.Controllers
{
    public class TacheController : Controller
    {
        private readonly ITaskRepository _taskRepository;
        private readonly IPersonneRepository _personRepository;
        public TacheController(ITaskRepository taskRepository, IPersonneRepository personRepository)
        {
            _taskRepository = taskRepository;
            _personRepository = personRepository;
        }

        public IActionResult Index()
        {
            var response = _taskRepository.Execute(new ArchNet_GestTask.Domains.Queries.GetAllTaskQuery());
            if (response.IsSuccess && response.Result!.Count() > 0)
            {
                List<TaskDisplayForm> tasks = response.Result!.Select(t => t.ToTaskDisplay()).ToList();
                return View(tasks);
            }
            return View();
        }

        public IActionResult TacheEtPersonne()
        {
            var response = _taskRepository.Execute(new GetAllTaskWithPersonQuery());
            if (response.IsSuccess && response.Result!.Count() > 0)
            {
                List<TaskWithPersonForm> tasks = response.Result.Select(t => t.ToTaskWithPerson()).ToList();
                return View(tasks);
            }
            return View();
        }

        public IActionResult PartialPersonne()
        {
            return new PartialViewResult()
            {
                ViewName = "PartialPersonne"
            };
        }

        public IActionResult Details(int id)
        {
            var response = _taskRepository.Execute(new GetOneTaskQuery(id));
            if (response.IsSuccess && response.Result != null)
            {
                TaskDisplayDetailsForm task = response.Result.ToTaskDisplayDetail();
                return View(task);
            }

            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateTaskForm form)
        {
            var response = _taskRepository.Execute(new CreateTaskCommand(form.Title, form.Description));
            if (response.IsSuccess)
                return RedirectToAction("Index");
            
            return View();
        }

        public IActionResult Edit(int id)
        {
            var response = _taskRepository.Execute(new GetOneTaskQuery(id));
          
                TaskUpdateForm task = response.Result.ToTaskUpdate();
            if (response.IsSuccess)
                return View(task);

            return View();
        }

        [HttpPost]
        public IActionResult Edit(TaskUpdateForm form, int id)
        {
            var response = _taskRepository.Execute(new UpdateTaskCommand(id, form.Title, form.Description));
            if (response.IsSuccess)
                return RedirectToAction("Details", new { id });

            return View();
        }

        
        public IActionResult Complete(int id)
        {
            Console.WriteLine(id);
            var response = _taskRepository.Execute(new FinishTaskCommand(id));
            if (response.IsSuccess)
                return RedirectToAction("Details", new { id });

            return View();
        }

        public IActionResult Assign(int id)
        {
            AssignTaskForm form = new AssignTaskForm();
            var response = _personRepository.Execute(new GetAllPersonneQuery());
            if (response.IsSuccess)
            {
                form.People = response.Result.Select(p => p.ToPersonDisplay()).ToList();
                return View(form);
            } else
            {
                return View();
            }
        }
        [HttpPost]
        public IActionResult Assign(AssignTaskForm form, int id)
        {
            Console.WriteLine(form.PersonId);
            var response = _taskRepository.Execute(new AssignTaskCommand(id, form.PersonId));
            if (response.IsSuccess)
                return RedirectToAction("Details", new { id });

        return View(form);
        }

        public IActionResult Partial() 
        {
			if (ViewData.ContainsKey("TaskId") && ViewData["TaskId"] is int taskId)
			{

				var response = _taskRepository.Execute(new GetOneTaskQuery(taskId));
				if (response.IsSuccess && response.Result != null)
				{
					TaskDisplayDetailsForm task = response.Result.ToTaskDisplayDetail();
					return PartialView(task);
				}

			}
			return new PartialViewResult
			{
				ViewName = "Partial",
			};
		}

	}
}

Arch_GestTask.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gestion des tâches</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Arch_GestTask.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: lightgrey;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link mycolor" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mycolor" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle mycolor" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Tâches et personnes
                            </a>
                            <ul class="dropdown-menu">
                                <li> <a class="nav-link text-dark border-bottom" asp-area="" asp-controller="Personne" asp-action="Index">Liste des personnes</a></li>
                                <li> <a class="nav-link text-dark border-bottom" asp-area="" asp-controller="Tache" asp-action="Index">Liste des Taches</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Tache" asp-action="TacheEtPersonne">Liste des Taches avec les personnes assignées</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Personne" asp-action="PersonneEtTache">Liste des personnes avec leurs taches</a></li>

                            </ul>
                        </li>
                    
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
@*         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Arch_GestTask.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personne" asp-action="Index">Liste des personnes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tache" asp-action="Index">Liste des Taches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tache" asp-action="TacheEtPersonne">Liste des Taches avec les personnes assignées</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Arch_GestTask.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>